.balign 64
tokenLiterals:
.balign 16
.asciz "boolean"
.balign 16
.asciz "signed"
.balign 16
.asciz "unsigned"
.balign 16
.asciz "integer64"
.balign 16
.asciz "integer8"
.balign 16
.asciz "0x"
.balign 16
.asciz "0d"
.balign 16
.asciz "0b"
.balign 16
.asciz "pop"
.balign 16
.asciz "pop2"
.balign 16
.asciz "systemExit"
.balign 16
.asciz "clearStack"
.balign 16
.asciz "count"
.balign 16
.asciz "duplicate"
.balign 16
.asciz "exchange"
.balign 16
.asciz "index"
.balign 16
.asciz "negate"
.balign 16
.asciz "add"
.balign 16
.asciz "multiply"
.balign 16
.asciz "equal"
.balign 16
.asciz "greaterThan"
.balign 16
.asciz "bitShiftDown"
.balign 16
.asciz "bitShiftUp"
.balign 16
.asciz "bitRotateDown"
.balign 16
.asciz "bitRotateUp"
.balign 16
.asciz "toBoolean"
.balign 16
.asciz "TRUE"
.balign 16
.asciz "FALSE"
.balign 16
.asciz "not"
.balign 16
.asciz "and"
.balign 16
.asciz "or"
.balign 16
.asciz "xor"
.balign 16
.asciz "maskBlend"
.balign 16
.asciz "callMaskBlend"
.balign 16
.asciz "call"
.balign 16
.asciz "callLess"
.balign 16
.asciz "callGreater"
.balign 16
.asciz "callEqual"
.balign 16
.asciz "callAnd"
.balign 16
.asciz "callNotLess"
.balign 16
.asciz "callNotGreater"
.balign 16
.asciz "callNotEqual"
.balign 16
.asciz "callNand"
.balign 16
.asciz "printStack"